apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service-jenkins
spec:
  selector:
    app: my-apps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 80
  type: NodePort  # Exposes the service on a port accessible from localhost
